#!/bin/bash
# Generated by Bob — review before executing
/opt/homebrew/bin/gh issue create \
  --repo Dr-Mohamed-Gamal/rta-salik-demo \
  --title "[BOB][Critical] Saturday/Sunday Weekday Check Inverted in tariff.py" \
  --label "bug" \
  --body "$(cat <<'EOF'
## Repro
```bash
pytest -k "test_saturday_is_offpeak_all_day or test_sunday_free_during_peak_hours or test_weekday_rules or test_sunday_is_free_all_day"
```

## Expected
- **Saturday (weekday=5):** Should return OFFPEAK_TOLL (AED 4.00) for all hours outside free window (01:00-06:00)
- **Sunday (weekday=6):** Should return FREE (AED 0.00) for all hours (entire day is free per RTA tariff schedule)

Per test plan scenarios:
- **T-H10:** Saturday is off-peak all day
- **T-H11:** Sunday free even during what would be peak hours on weekdays

## Actual
- **Saturday:** Returns FREE (AED 0.00) — incorrectly treated as free day
- **Sunday:** Returns OFFPEAK_TOLL (AED 4.00) or PEAK_TOLL (AED 6.00) — incorrectly charged

**Assertions from junit.xml:**
- `assert Decimal('0.00') == Decimal('4.00')` (Saturday tests)
- `assert Decimal('4.00') == Decimal('0.00')` (Sunday tests)

## Suggested fix
```diff
--- a/salik/tariff.py
+++ b/salik/tariff.py
@@ -27,7 +27,7 @@ def toll_for(when: datetime) -> Decimal:
     if FREE_WINDOW[0] <= t < FREE_WINDOW[1]:
         return FREE
     # Sunday is a free day. Python: Monday=0 … Sunday=6.
-    if when.weekday() == 5:
+    if when.weekday() == 6:
         return FREE
     if when.weekday() < 5:
         for start, end in PEAK_WINDOWS:
```

**Explanation:**
Python datetime.weekday() returns Monday=0, Tuesday=1, ..., Saturday=5, Sunday=6. The bug changed the check from == 6 (Sunday) to == 5 (Saturday), causing Saturday to be treated as the free day instead of Sunday.

## Symptoms (5 failing tests — all one root cause)
1. **tests/test_generated_tariff.py:43** — `test_saturday_is_offpeak_all_day` (Scenario T-H10)
2. **tests/test_generated_tariff.py:49** — `test_sunday_free_during_peak_hours` (Scenario T-H11)
3. **tests/test_generated_tariff.py:76** — `test_weekday_rules[5-7-expected5]` (Scenario T-H10 parametrized)
4. **tests/test_generated_tariff.py:76** — `test_weekday_rules[6-7-expected6]` (Scenario T-H11 parametrized)
5. **tests/test_tariff.py:18** — `test_sunday_is_free_all_day` (existing baseline test)

## Impact
**Severity: Critical**
- **Revenue:** 100% loss on Saturday tolls (uncollected); refund liability for incorrectly charged Sunday tolls
- **Driver Fairness:** Saturday drivers receive unintended free passes; Sunday drivers wrongly charged
- **Legal/Regulatory:** Violates published RTA tariff schedule
- **Scope:** Affects 2 out of 7 days (28.6% of the week)

## Artifacts
- reports/junit.xml
- reports/coverage.xml
- reports/analysis.md
EOF
)"

# Made with Bob
